//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace My
{
    //This class was auto-generated by the StronglyTypedResourceBuilder
    //class via a tool like ResGen or Visual Studio.
    //To add or remove a member, edit your .ResX file then rerun ResGen
    //with the /str option, or rebuild your VS project.
    /// <summary>
    ///  A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualBasic.HideModuleNameAttribute()]
    internal static class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///  Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NHunspellExtender.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///  Overrides the current thread's CurrentUICulture property for all
        ///  resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///  Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] en_US
        {
            get
            {
                object obj = ResourceManager.GetObject("en_US", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        ///  Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] en_US_dic
        {
            get
            {
                object obj = ResourceManager.GetObject("en_US_dic", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        ///  Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_go
        {
            get
            {
                object obj = ResourceManager.GetObject("folder_go", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        ///  Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hunspellx64
        {
            get
            {
                object obj = ResourceManager.GetObject("Hunspellx64", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        ///  Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hunspellx86
        {
            get
            {
                object obj = ResourceManager.GetObject("Hunspellx86", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        ///  Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NHunspell
        {
            get
            {
                object obj = ResourceManager.GetObject("NHunspell", resourceCulture);
                return (byte[])obj;
            }
        }

        /// <summary>
        ///  Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spellcheck
        {
            get
            {
                object obj = ResourceManager.GetObject("spellcheck", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }
    }
}


